# Generated by Django 4.2.21 on 2025-06-16 10:00

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='video',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_file',
            field=models.ImageField(blank=True, help_text='Upload thumbnail image', null=True, upload_to=api.models.thumbnail_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (max 500MB)', null=True, upload_to=api.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'])]),
        ),
        migrations.AddField(
            model_name='video',
            name='video_quality',
            field=models.CharField(default='1080p', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
